//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Payment')
export class PaymentEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  userId: number;

  @Column('real', { nullable: true })
  amount: number;

  @Column('text', { nullable: true })
  paymentMethod: string;

  @Column('text', { nullable: true })
  transactionId: string;

  @Column('date', { nullable: true })
  paymentDate: Date;
}
