//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="best basketball tips" />
    <CardContent>
      i want to have free and and vip sections for subscribers, and vip members
      will pay 10dollar to subscribe for VIP section using airtel money
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
